# Generated by Django 2.1.5 on 2019-01-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('numero_guia_consulta', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_medico', models.IntegerField()),
                ('nome_medico', models.CharField(blank=True, max_length=5000, null=True)),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('valor_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('cod_exame', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_exame', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('numero_guia_consulta', models.ForeignKey(db_column='numero_guia_consulta', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.Consulta')),
            ],
            options={
                'db_table': 'exame',
            },
        ),
        migrations.AlterUniqueTogether(
            name='exame',
            unique_together={('cod_exame', 'numero_guia_consulta')},
        ),
    ]
