# Generated by Django 2.1.5 on 2019-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='numero_guia_consulta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
